### PR TITLE
Screenshots use mobile emulation and don't strip page using it

### LINKED ISSUE #40: Screenshots should probably be using mobile emulation to get rid of ugly scrollbars and weirdness

### PR DESCRIPTION
**Pull request by samuelli**
Fixes #40.

Prior to this change, the `stripPage()` function was called. When combined with `link rel='import'` and scoped style (without shady DOM/CSS enabled), screenshots would appear different from expected.

This change moves the `stripPage()` function call to just the `render` endpoint. This also uses mobile emulation, which allows for viewport meta tag, overlay scrollbars, text autosizing. See [the docs](https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setDeviceMetricsOverride) for more details on the implications of mobile emulation.

### CODE REVIEW

**Comment by wapiflapi** [comment]
@samuelli I stumbled upon this pull request while debugging a rendering issue for screenshots of some websites. My problem is it looks like the page didn't finish rendering with random "rectangular chunks" missing towards the bottom of the page.

It turns out that when I set `deviceScaleFactor` to `1.0` instead of `3.5` it fixes my problem. I'm not sure why this is. I was wondering if you could explain why you choose `3.5` as opposed to (the intuitive?) `1.0` that seems to work for me. I don't notice any difference on other websites.

**Comment by samuelli** [comment]
@wapiflapi: do you have a test URL for the issue? I don't recall why I set it to `3.5` - its probably fine to change it to `1.0`.

**Comment by wapiflapi** [comment]
I did some more digging and it looks like the culprit is the theme the site uses, so here is another example that (doesn't) work with `3.5` and a high enough resolution. (1920x1080 doesn't work for me.)

Fetching a screenshot for the url http://www.newsmartwave.net/wordpress/porto/ using:
```
http://localhost:3000/screenshot/http://www.newsmartwave.net/wordpress/porto/?width=1920&height=1080
```

I get the following screenshot:
foo

**Comment by samuelli** [comment]
@wapiflapi: #121. Yeah, an issue probably would've been better. I opened a PR with some interesting findings.

**Pull request merged**
